### ISSUE TITLE
Study location needs to be made optional

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#33]
The script fails when users are present with no study location (and probably also when there is another location like work missing).
````
nate@nate-worklap:~/itinerum/itinerum-trip-breaker$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    school = Location(row['location_study_lon'], row['location_study_lat'])
  File "/home/nate/itinerum/itinerum-trip-breaker/location.py", line 6, in __init__
    self.latitude = float(latitude)
ValueError: could not convert string to float: 
````
The string in question is empty: `''`

**Comment by felipevh** [comment]
Removed reference to study location for now since it isn't used in the analysis.
