### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#43]
````
nate@nate-worklap:~/itinerum/itinerum-trip-breaker$ python3 main.py
3 user(s) to clean
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    user = Trace(user_id, user_ids[user_id], survey_responses[user_id])
  File "/home/nate/itinerum/itinerum-trip-breaker/trace.py", line 29, in __init__
    h = read_headers()
TypeError: read_headers() missing 1 required positional argument: 'fname'
````

**Comment by Nate-Wessel** [comment]
Fixed

**Comment by Nate-Wessel** [comment]
read_headers() was being called without an argument and was in the code without any apparent purpose.
